# Generated by Django 2.2.5 on 2020-09-11 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_jay_user_bio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Jay_User',
        ),
    ]
