# Generated by Django 2.2.5 on 2020-09-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
