# Generated by Django 2.2.5 on 2020-09-11 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20200911_1230'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
